// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(
        oneof = "client_message::Msg",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24"
    )]
    pub msg: ::core::option::Option<client_message::Msg>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Handshake(super::ConnectHandshake),
        #[prost(message, tag = "2")]
        SelectChat(super::SelectChat),
        #[prost(message, tag = "3")]
        RequestBacklog(super::RequestBacklog),
        #[prost(message, tag = "4")]
        SendText(super::SendText),
        #[prost(message, tag = "5")]
        SendMedia(super::SendMedia),
        #[prost(message, tag = "6")]
        MarkRead(super::MarkRead),
        #[prost(message, tag = "7")]
        MarkUnread(super::MarkUnread),
        #[prost(message, tag = "8")]
        Login(super::LoginRequest),
        #[prost(message, tag = "9")]
        Disconnect(super::DisconnectRequest),
        #[prost(message, tag = "10")]
        Logout(super::LogoutRequest),
        #[prost(message, tag = "11")]
        DownloadMedia(super::DownloadMedia),
        #[prost(message, tag = "12")]
        OpenMedia(super::OpenMedia),
        #[prost(message, tag = "13")]
        Revoke(super::RevokeMessage),
        #[prost(message, tag = "14")]
        LeaveGroup(super::LeaveGroup),
        #[prost(message, tag = "15")]
        CreateGroup(super::CreateGroup),
        #[prost(message, tag = "16")]
        GroupMember(super::GroupMember),
        #[prost(message, tag = "17")]
        SetSubject(super::SetSubject),
        #[prost(message, tag = "18")]
        GetInfo(super::GetInfo),
        #[prost(message, tag = "19")]
        GetUrl(super::GetUrl),
        #[prost(message, tag = "20")]
        ShowMedia(super::ShowMedia),
        #[prost(message, tag = "21")]
        SendImage(super::SendImageCommand),
        #[prost(message, tag = "22")]
        SendVideo(super::SendVideoCommand),
        #[prost(message, tag = "23")]
        SendAudio(super::SendAudioCommand),
        #[prost(message, tag = "24")]
        ForceTranslate(super::ForceTranslate),
    }
}
/// First message on the Connect stream — client metadata, not a user action.
/// Also re-sent on terminal resize.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectHandshake {
    #[prost(int32, tag = "1")]
    pub viewport_rows: i32,
    #[prost(int32, tag = "2")]
    pub viewport_cols: i32,
    #[prost(string, tag = "3")]
    pub client_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectChat {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(enumeration = "select_chat::Intent", tag = "2")]
    pub intent: i32,
}
/// Nested message and enum types in `SelectChat`.
pub mod select_chat {
    /// How strongly the client believes the user wants this chat.
    ///
    /// Drives the backend's auto-mark-as-read behaviour: PROBE selections (e.g.
    /// arrow-key navigation through the chat list) defer the read receipt until
    /// the user dwells on the chat, while COMMIT selections (e.g. Enter on a
    /// chat row, or focus shifting into the composer) fire the read receipt
    /// immediately. The chat content itself is loaded the same way for both,
    /// so the user can see the messages instantly while still keeping unread
    /// chats unread until they actually settle on one.
    ///
    /// Defaulting to PROBE preserves the safer behaviour for any client that
    /// doesn't yet understand this field.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Intent {
        Probe = 0,
        Commit = 1,
    }
    impl Intent {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Probe => "PROBE",
                Self::Commit => "COMMIT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PROBE" => Some(Self::Probe),
                "COMMIT" => Some(Self::Commit),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RequestBacklog {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendText {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMedia {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "3")]
    pub kind: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkRead {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkUnread {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoginRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisconnectRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LogoutRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadMedia {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenMedia {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShowMedia {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeMessage {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveGroup {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroup {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMember {
    #[prost(enumeration = "group_member::Action", tag = "1")]
    pub action: i32,
    #[prost(string, repeated, tag = "2")]
    pub participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Nested message and enum types in `GroupMember`.
pub mod group_member {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Action {
        Add = 0,
        Remove = 1,
        Promote = 2,
        Demote = 3,
    }
    impl Action {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Add => "ADD",
                Self::Remove => "REMOVE",
                Self::Promote => "PROMOTE",
                Self::Demote => "DEMOTE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ADD" => Some(Self::Add),
                "REMOVE" => Some(Self::Remove),
                "PROMOTE" => Some(Self::Promote),
                "DEMOTE" => Some(Self::Demote),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetSubject {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInfo {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUrl {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
/// Re-translate a message right now, bypassing the per-message translation
/// classifier and any cached result. Used by the manual "translate this
/// anyway" shortcut so the user can always override our heuristics in one
/// keystroke when we got it wrong (e.g. classified a Spanish message as
/// English in a mixed-language thread). The server emits a fresh
/// NewTranslation event when it succeeds.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForceTranslate {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendImageCommand {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendVideoCommand {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendAudioCommand {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEvent {
    #[prost(
        oneof = "server_event::Event",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub event: ::core::option::Option<server_event::Event>,
}
/// Nested message and enum types in `ServerEvent`.
pub mod server_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        ChatList(super::ChatList),
        #[prost(message, tag = "2")]
        ChatMessages(super::ChatMessages),
        #[prost(message, tag = "3")]
        NewMessage(super::NewMessage),
        #[prost(message, tag = "4")]
        NewTranslation(super::NewTranslation),
        #[prost(message, tag = "5")]
        NewTranscription(super::NewTranscription),
        #[prost(message, tag = "6")]
        StatusUpdate(super::StatusUpdate),
        #[prost(message, tag = "7")]
        ErrorEvent(super::ErrorEvent),
        #[prost(message, tag = "8")]
        InfoText(super::InfoText),
        #[prost(message, tag = "9")]
        FileReady(super::FileReady),
        #[prost(message, tag = "10")]
        OpenFile(super::OpenFileRequest),
        #[prost(message, tag = "11")]
        ModelProgress(super::ModelProgress),
        #[prost(message, tag = "12")]
        ColorList(super::ColorList),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatList {
    #[prost(message, repeated, tag = "1")]
    pub chats: ::prost::alloc::vec::Vec<ChatProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessages {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<MessageProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewMessage {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<MessageProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewTranslation {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub translated_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewTranscription {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transcribed_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusUpdate {
    #[prost(int32, tag = "1")]
    pub battery_charge: i32,
    #[prost(bool, tag = "2")]
    pub battery_loading: bool,
    #[prost(bool, tag = "3")]
    pub battery_powersave: bool,
    #[prost(bool, tag = "4")]
    pub connected: bool,
    #[prost(string, tag = "5")]
    pub last_seen: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorEvent {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoText {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileReady {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenFileRequest {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelProgress {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub downloaded_bytes: i64,
    #[prost(int64, tag = "3")]
    pub total_bytes: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ColorList {
    #[prost(string, repeated, tag = "1")]
    pub colors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaChunk {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub total_size: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginEvent {
    #[prost(oneof = "login_event::Event", tags = "1, 2, 3, 4")]
    pub event: ::core::option::Option<login_event::Event>,
}
/// Nested message and enum types in `LoginEvent`.
pub mod login_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        QrCode(super::QrCode),
        #[prost(message, tag = "2")]
        Success(super::LoginSuccess),
        #[prost(message, tag = "3")]
        Timeout(super::LoginTimeout),
        #[prost(message, tag = "4")]
        Error(super::LoginError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QrCode {
    #[prost(bytes = "vec", tag = "1")]
    pub png_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoginSuccess {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoginTimeout {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_group: bool,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub unread: i32,
    #[prost(int64, tag = "5")]
    pub last_message: i64,
    #[prost(bool, tag = "6")]
    pub archived: bool,
    #[prost(bool, tag = "7")]
    pub pinned: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sender_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub contact_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub contact_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub contact_short: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
    #[prost(bool, tag = "8")]
    pub from_me: bool,
    #[prost(bool, tag = "9")]
    pub forwarded: bool,
    #[prost(string, tag = "10")]
    pub text: ::prost::alloc::string::String,
    #[prost(enumeration = "MessageKind", tag = "11")]
    pub kind: i32,
    #[prost(string, tag = "12")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "14")]
    pub unread: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageKind {
    Text = 0,
    Image = 1,
    Video = 2,
    Audio = 3,
    Document = 4,
    Unknown = 5,
}
impl MessageKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Text => "TEXT",
            Self::Image => "IMAGE",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
            Self::Document => "DOCUMENT",
            Self::Unknown => "UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TEXT" => Some(Self::Text),
            "IMAGE" => Some(Self::Image),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            "DOCUMENT" => Some(Self::Document),
            "UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod whats_cli_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct WhatsCliClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WhatsCliClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WhatsCliClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WhatsCliClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            WhatsCliClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional event stream. The first ClientMessage MUST be a
        /// ConnectHandshake; the server rejects the stream otherwise.
        pub async fn event_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ClientMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServerEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/whatscli.WhatsCLI/EventStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("whatscli.WhatsCLI", "EventStream"));
            self.inner.streaming(req, path, codec).await
        }
        /// Stream media bytes for a given message. Separated from Connect to avoid
        /// blocking the main event stream with large payloads.
        pub async fn get_media(
            &mut self,
            request: impl tonic::IntoRequest<super::MediaRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MediaChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/whatscli.WhatsCLI/GetMedia",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("whatscli.WhatsCLI", "GetMedia"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// QR-code login flow. Server streams QR updates until the device is paired
        /// or the timeout expires.
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LoginEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/whatscli.WhatsCLI/Login");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("whatscli.WhatsCLI", "Login"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
